name: Bug/Crash Report
description: Open an issue here
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug/crash
      description: Tell me what bug you encountered and what should have happened
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Please write the steps in a list form
    validations:
      required: true
  - type: textarea
    id: player-log
    attributes:
      label: Player.log
      description: Add the file "Player.log" that contains the crash/bug by dragging it into this input field. The Message shown during a crash is NOT a log and not helpful. The log file can be found here:\
Windows:\
C:\Users%username%\AppData\LocalLow\Klei\Oxygen Not Included\Player.log
Mac:\
~/Library/Logs/Klei/Oxygen Not Included/Player.log
Linux:\
~/.config/unity3d/Klei/Oxygen Not Included/Player.log
      
    validations:
      required: true